# Site settings
title: DevNaEstrada
email: devnaestrada at gmail com
email_address: devnaestrada@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
description: "Podcast sobre front-end, back-end e desenvolvimento web. Venha conhecer o nosso ponto de vista no mundo da programação!"
url: "http://devnaestrada.com.br" # the base hostname & protocol for your site

# itunes
itunes_url: "https://itunes.apple.com/br/podcast/devnaestrada/id997779431?mt=2"
itunes_itpc: "itpc://devnaestrada.com.br/feed.xml"

# soundcloud
soundcloud_prefix: "http://feeds.soundcloud.com/stream/"
soundcloud_site_capa: "http://i1.sndcdn.com/avatars-000147816775-ycyu5k-original.jpg"

# vendor codes
google_analytics: UA-63291340-1
disqus_shortname: devnaestrada
facebook_meta: true

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - bourbon
  - neat