# Site settings
title: DevNaEstrada
email: devnaestrada at gmail com
email_address: devnaestrada@gmail.com
baseurl: "/"
description: "Podcast sobre front-end, back-end e desenvolvimento web. Venha conhecer o nosso ponto de vista no mundo da programação!"
url: "http://devnaestrada.com.br"

# Blog
paginate: 6
paginate_path: "/podcast/:num/"

# social links
github_user: "devnaestrada"
twitter_user: "devnaestrada"
soundcloud_user: "devnaestrada"
facebook_user: "devnaestrada"

# itunes
itunes_url: "https://itunes.apple.com/br/podcast/devnaestrada/id997779431?mt=2"
itunes_itpc: "itpc://devnaestrada.com.br/feed.xml"

# soundcloud
soundcloud_prefix: "http://feeds.soundcloud.com/stream/"
soundcloud_site_capa: "http://i1.sndcdn.com/avatars-000161212924-uhi3ws-original.png"

# vendor codes
google_analytics: UA-63291340-1
disqus_shortname: devnaestrada
facebook_meta: true

# Build settings
markdown: kramdown

# Sass configuration
sass:
  sass_dir: public/assets/scss
  style: compressed

gems:
  - jekyll-sitemap
  - bourbon
  - neat